## CREATE the Student Database

In [78]:
students <- data.frame(
  Student_ID=c("S001","S002","S003","S004","S005","S006","S007","S008"),
  Programming_Grade=c(88,72,91,78,65,85,74,82),
  Math_Grade=c(85,70,88,80,68,90,73,79),
  Attendance=c(92,80,95,88,70,91,76,85),
  Prerequisite=c("Yes","No","Yes","Yes","No","Yes","No","Yes")
)

write.csv(students,"Students.csv")

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

##Explore the Data

In [54]:
data <- read.csv("Students.csv")

head(data)
cat("\n")
summary(data)

  X Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 1 S001       88                85         92         Yes
2 2 S002       72                70         80         No
3 3 S003       91                88         95         Yes
4 4 S004       78                80         88         Yes
5 5 S005       65                68         70         No
6 6 S006       85                90         91         Yes

       X            Student_ID Programming_Grade   Math_Grade
 Min.   :1.00   Length   :8    Min.   :65.00     Min.   :68.00
 1st Qu.:2.75   N.unique :8    1st Qu.:73.50     1st Qu.:72.25
 Median :4.50   N.blank  :0    Median :80.00     Median :79.50
 Mean   :4.50   Min.nchar:4    Mean   :79.38     Mean   :79.12
 3rd Qu.:6.25   Max.nchar:4    3rd Qu.:85.75     3rd Qu.:85.75
 Max.   :8.00                  Max.   :91.00     Max.   :90.00
   Attendance       Prerequisite
 Min.   :70.00   Length   :8
 1st Qu.:79.00   N.unique :2
 Median :86.50   N.blank  :0
 Mean   :84.62   Min.nchar:2
 3rd Qu.:91.25   Max.nchar:3
 Max.   :95.00

In [35]:
col <- ncol(students)
row <- nrow(students)

cat ("Rows:", row ,"\n")
cat ("Column:", col ,"\n")

cat ("Max Attendance:", max(students$Attendance))

Rows: 8
Column: 5
Max Attendance: 95

## Enter a Student ID

In [46]:
student_ID = readline("Enter Student ID: ")
print(student_ID)

Enter Student ID: S2023
[1] "S2023"

## Search the Data Frame

In [41]:
students <- students[
  students$Student_ID == student_ID,
]
students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

In [47]:
students <- students[
  students$Student_ID != student_ID,
  print("Not Found")
]
students

[1] "Not Found"

NULL

In [106]:
student_ID_input = readline("Enter Student ID: ")
print(student_ID_input)


filtered_students <- students[students$Student_ID == student_ID_input, ]


if (nrow(filtered_students) > 0) {
  students <- filtered_students
  print(students)
} else {
  print("Student ID not found. 'students' data frame is now empty.")
}

print(students)

Enter Student ID: S001
[1] "S001"
[1] "Student ID not found. 'students' data frame is now empty."
[1] Student_ID        Programming_Grade Math_Grade        Attendance
[5] Prerequisite      Eligbility        Recommendation
<0 rows> (or 0-length row.names)

## Extract Students Information

In [71]:
programming <- students$Programming_Grade

cat("Programming Grade: ", programming)

Programming Grade:  88 72 91 78 65 85 74 82

## Implement the Rules

In [93]:
classify_Eligibility <- function (Programming_Grade, Math_Grade, Attendance, Prerequisite){
  if (Programming_Grade >= 80 && Math_Grade >= 75 && Attendance >= 80 && Prerequisite == "Yes"){
  print("Eligible")
} else if (Programming_Grade >= 75 && Math_Grade >= 70 && Attendance >= 75) {
  print("Conditionally Eligible")
} else {
  print("Not Eligible")
}
}

## Apply the Functions to All Students

In [94]:
students$Eligbility <- mapply(
  classify_Eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite

)

students

[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Conditionally Eligible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligbility
1 Eligible
2 Not Eligible
3 Eligible
4 Conditionally Eligible
5 Not Eligible
6 Eligible
7 Not Eligible
8 Eligible

## Create Recommendation Rules

In [102]:
student_Recommendations <- function(classify_Eligibility)
{
  if (classify_Eligibility == "Eligible") {
  return ("Student May Enroll")
} else if (classify_Eligibility == "Conditionally Eligible"){
  return ("Consult Academic Tutor")
} else if (classify_Eligibility == "Not Eligible"){
  return ("Complete Requirements Before Enrollment")
}
}

students$Recommendation <- sapply(
  students$Eligbility,
  student_Recommendations
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligbility             Recommendation
1 Eligible               Student May Enroll
2 Not Eligible           Complete Requirements Before Enrollment
3 Eligible               Student May Enroll
4 Conditionally Eligible Consult Academic Tutor
5 Not Eligible           Complete Requirements Before Enrollment
6 Eligible               Student May Enroll
7 Not Eligible           Complete Requirements Before Enrollment
8 Eligible               Student May Enroll

## Complete the table

In [104]:
student_id <- readline(prompt = "Enter Student ID: ")

student <- students[students$Student_ID == student_id, ]

if (nrow(student) > 0) {

  cat("\n========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat(sprintf("Programming Grade: %.2f%%\n", student$Programming_Grade))
  cat(sprintf("Math Grade: %.2f%%\n", student$Math_Grade))
  cat(sprintf("Attendance: %.2f%%\n", student$Attendance))
  cat("Prerequisite:", student$Prerequisite, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Eligibility, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n")

  cat("========================================\n")

} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S001

========================================
       COURSE ENROLLMENT ADVISER
========================================

Student ID: S001

Programming Grade: 88.00%
Math Grade: 85.00%
Attendance: 92.00%
Prerequisite: Yes

Enrollment Status:


Recommendation:
Student May Enroll
========================================